version: '3'
services:
    mongodb_logs:
        container_name: ${API_NAME}-logs-mongodb
        image: mongo:latest
        restart: always
        ports:
            - ${LOG_MONGODB_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${LOG_MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${LOG_MONGODB_PASSWORD}
        volumes:
            - ./.docker/mongodb/entrypoints/logs-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./.docker/mongodb/datas/logs:/data/db
    mongodb_accounts:
        container_name: ${API_NAME}-accounts-mongodb
        image: mongo:latest
        restart: always
        ports:
            - ${ACCOUNT_MONGODB_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${ACCOUNT_MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${ACCOUNT_MONGODB_PASSWORD}
        volumes:
            - ./.docker/mongodb/entrypoints/accounts-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./.docker/mongodb/datas/accounts:/data/db
